// Public Amazon dispute portal client. Talks to the disputePortalApi Lambda Function URL.
// URL priority: VITE_DISPUTE_PORTAL_API_URL env var → amplify_outputs.json custom.disputePortalUrl.
import outputs from '../../amplify_outputs.json'

const envUrl: string | undefined =
  typeof import.meta.env.VITE_DISPUTE_PORTAL_API_URL === 'string'
    ? import.meta.env.VITE_DISPUTE_PORTAL_API_URL
    : undefined

// amplify_outputs.json is generated by the Amplify build pipeline; we expect the optional
// custom.disputePortalUrl value when the backend defines it.
const rawOutputs = outputs as { custom?: { disputePortalUrl?: unknown } | undefined }
const customUrl: string | undefined =
  typeof rawOutputs.custom?.disputePortalUrl === 'string' ? rawOutputs.custom.disputePortalUrl : undefined

export const DISPUTE_PORTAL_API_URL = envUrl ?? customUrl ?? ''
export const portalAvailable = !!DISPUTE_PORTAL_API_URL

export class DisputePortalError extends Error {
  status: number
  constructor(status: number, message: string) {
    super(message)
    this.status = status
  }
}

export type DisputeStatus = 'PENDING' | 'POSTED' | 'PAID' | 'REJECTED'
export type ProofKind = 'CONFIRMATION' | 'PHOTO'

export interface BoardItem {
  id: string
  driverName: string
  tripNumber?: string | null
  payPeriod?: string | null
  shipmentDate?: string | null
  status: DisputeStatus
  resolvedAmount?: number | null
}

export interface EvidenceFile {
  s3Key: string
  fileName: string
  contentType: string
  size: number
  kind: ProofKind
}

export interface UploadUrlResponse {
  uploadUrl: string
  s3Key: string
}

function extractMessage(data: unknown, fallback: string): string {
  if (data && typeof data === 'object' && 'error' in data && typeof data.error === 'string') {
    return data.error
  }
  return fallback
}

async function post<T>(action: string, payload?: unknown): Promise<T> {
  if (!DISPUTE_PORTAL_API_URL) {
    throw new DisputePortalError(0, 'Dispute portal endpoint is not configured')
  }
  const res = await fetch(DISPUTE_PORTAL_API_URL, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ action, payload }),
  })
  const data = await res.json().catch(() => ({}))
  if (!res.ok) {
    throw new DisputePortalError(res.status, extractMessage(data, res.statusText))
  }
  return data as T
}

export async function listDisputes(
  nextToken?: string,
): Promise<{ items: BoardItem[]; nextToken?: string | null }> {
  return post('list', nextToken ? { nextToken } : undefined)
}

/** Active drivers' names for the form's dropdown - the only Driver data the public endpoint exposes. */
export async function listDrivers(): Promise<string[]> {
  const res = await post<{ drivers?: unknown }>('drivers')
  return Array.isArray(res.drivers) ? res.drivers.filter((d): d is string => typeof d === 'string') : []
}

export async function getUploadUrl(opts: {
  submissionId: string
  fileName: string
  contentType: string
  size: number
  kind: ProofKind
}): Promise<UploadUrlResponse> {
  return post('upload', opts)
}

export interface SubmitInput {
  submissionId: string
  driverName: string
  tripNumber: string
  payPeriod: string
  shipmentDate: string
  amountPaid: number
  amountRequested: number
  description: string
  evidence: EvidenceFile[]
}

export async function submitDispute(input: SubmitInput): Promise<{ ok: true; id: string }> {
  return post('submit', input)
}

/** Upload a file to the presigned S3 URL. `contentType` must be the value the URL was
 *  signed for (the browser's file.type may be empty). The If-None-Match: * header is sent
 *  so retries can be idempotent when the backend signs that header. */
export async function uploadFileToS3(file: File, uploadUrl: string, contentType: string): Promise<void> {
  const res = await fetch(uploadUrl, {
    method: 'PUT',
    body: file,
    headers: {
      'content-type': contentType,
      'content-length': String(file.size),
      'If-None-Match': '*',
    },
  })
  if (!res.ok) {
    throw new DisputePortalError(res.status, `Upload failed: ${res.status} ${res.statusText}`)
  }
}

/** Stable submission id for the browser session. */
export function uuid(): string {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    return crypto.randomUUID()
  }
  // Fallback for rare environments without crypto.randomUUID.
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`
}
