import { Amplify } from 'aws-amplify'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App'

// amplify_outputs.json is generated by Amplify during the build pipeline.
// The placeholder file in the repo is replaced with real values on every deploy.
// For local dev, run: npx ampx sandbox
import outputs from '../amplify_outputs.json'
Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0])

createRoot(document.getElementById('root')!).render(
  <App />
)
